export const ActionType = {
  FETCH_FILMS_REQUEST : 'FETCH_FILMS_REQUEST',
  FETCH_FILMS_SUCCESS : 'FETCH_FILMS_SUCCESS',
  FETCH_FILMS_ERROR : 'FETCH_FILMS_ERROR',

  FETCH_FILMS__BY_ID_REQUEST: 'FETCH_FILMS__BY_ID_REQUEST',
  FETCH_FILMS__BY_ID_SUCCESS: 'FETCH_FILMS__BY_ID_SUCCESS',
  FETCH_FILMS__BY_ID_ERROR: 'FETCH_FILMS__BY_ID_ERROR',

  DELETE_FILM_REQUEST : 'DELETE_FILM_REQUEST',
  DELETE_FILM_SUCCESS : 'DELETE_FILM_SUCCESS',
  DELETE_FILM_ERROR : 'DELETE_FILM_ERROR',

  ADD_FILM_REQUEST : 'ADD_FILM_REQUEST',
  ADD_FILM_SUCCESS : 'ADD_FILM_SUCCESS',
  ADD_FILM_ERROR : 'ADD_FILM_ERROR',

  SEARCH_TITLE_VALUE : "SEARCH_TITLE_VALUE",
  SEARCH_STARS_VALUE : "SEARCH_STARS_VALUE",
  SORT_METHOD : "SORT_VALUE",
};